// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

/**
 * Protobuf type {@code BirthDate}
 */
public final class BirthDate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BirthDate)
    BirthDateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BirthDate.newBuilder() to construct.
  private BirthDate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BirthDate() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BirthDate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BirthDate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder subBuilder = null;
            if (birthDatestamp_ != null) {
              subBuilder = birthDatestamp_.toBuilder();
            }
            birthDatestamp_ = input.readMessage(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(birthDatestamp_);
              birthDatestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_BirthDate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_BirthDate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.Builder.class);
  }

  public static final int BIRTHDATESTAMP_FIELD_NUMBER = 1;
  private com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp birthDatestamp_;
  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   * @return Whether the birthDatestamp field is set.
   */
  @java.lang.Override
  public boolean hasBirthDatestamp() {
    return birthDatestamp_ != null;
  }
  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   * @return The birthDatestamp.
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp getBirthDatestamp() {
    return birthDatestamp_ == null ? com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.getDefaultInstance() : birthDatestamp_;
  }
  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder getBirthDatestampOrBuilder() {
    return getBirthDatestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (birthDatestamp_ != null) {
      output.writeMessage(1, getBirthDatestamp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (birthDatestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBirthDatestamp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate)) {
      return super.equals(obj);
    }
    com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate other = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate) obj;

    if (hasBirthDatestamp() != other.hasBirthDatestamp()) return false;
    if (hasBirthDatestamp()) {
      if (!getBirthDatestamp()
          .equals(other.getBirthDatestamp())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBirthDatestamp()) {
      hash = (37 * hash) + BIRTHDATESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDatestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BirthDate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BirthDate)
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_BirthDate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_BirthDate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.Builder.class);
    }

    // Construct using com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (birthDatestampBuilder_ == null) {
        birthDatestamp_ = null;
      } else {
        birthDatestamp_ = null;
        birthDatestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_BirthDate_descriptor;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate getDefaultInstanceForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.getDefaultInstance();
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate build() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate buildPartial() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate result = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate(this);
      if (birthDatestampBuilder_ == null) {
        result.birthDatestamp_ = birthDatestamp_;
      } else {
        result.birthDatestamp_ = birthDatestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate) {
        return mergeFrom((com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate other) {
      if (other == com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate.getDefaultInstance()) return this;
      if (other.hasBirthDatestamp()) {
        mergeBirthDatestamp(other.getBirthDatestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp birthDatestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder> birthDatestampBuilder_;
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     * @return Whether the birthDatestamp field is set.
     */
    public boolean hasBirthDatestamp() {
      return birthDatestampBuilder_ != null || birthDatestamp_ != null;
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     * @return The birthDatestamp.
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp getBirthDatestamp() {
      if (birthDatestampBuilder_ == null) {
        return birthDatestamp_ == null ? com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.getDefaultInstance() : birthDatestamp_;
      } else {
        return birthDatestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public Builder setBirthDatestamp(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp value) {
      if (birthDatestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        birthDatestamp_ = value;
        onChanged();
      } else {
        birthDatestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public Builder setBirthDatestamp(
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder builderForValue) {
      if (birthDatestampBuilder_ == null) {
        birthDatestamp_ = builderForValue.build();
        onChanged();
      } else {
        birthDatestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public Builder mergeBirthDatestamp(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp value) {
      if (birthDatestampBuilder_ == null) {
        if (birthDatestamp_ != null) {
          birthDatestamp_ =
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.newBuilder(birthDatestamp_).mergeFrom(value).buildPartial();
        } else {
          birthDatestamp_ = value;
        }
        onChanged();
      } else {
        birthDatestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public Builder clearBirthDatestamp() {
      if (birthDatestampBuilder_ == null) {
        birthDatestamp_ = null;
        onChanged();
      } else {
        birthDatestamp_ = null;
        birthDatestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder getBirthDatestampBuilder() {
      
      onChanged();
      return getBirthDatestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder getBirthDatestampOrBuilder() {
      if (birthDatestampBuilder_ != null) {
        return birthDatestampBuilder_.getMessageOrBuilder();
      } else {
        return birthDatestamp_ == null ?
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.getDefaultInstance() : birthDatestamp_;
      }
    }
    /**
     * <code>.BirthDateStamp birthDatestamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder> 
        getBirthDatestampFieldBuilder() {
      if (birthDatestampBuilder_ == null) {
        birthDatestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder>(
                getBirthDatestamp(),
                getParentForChildren(),
                isClean());
        birthDatestamp_ = null;
      }
      return birthDatestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BirthDate)
  }

  // @@protoc_insertion_point(class_scope:BirthDate)
  private static final com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate();
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BirthDate>
      PARSER = new com.google.protobuf.AbstractParser<BirthDate>() {
    @java.lang.Override
    public BirthDate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BirthDate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BirthDate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BirthDate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

