// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface BirthDateStampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BirthDateStamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 day = 1;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 year = 3;</code>
   * @return The year.
   */
  int getYear();
}
