// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface BirthDateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BirthDate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   * @return Whether the birthDatestamp field is set.
   */
  boolean hasBirthDatestamp();
  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   * @return The birthDatestamp.
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStamp getBirthDatestamp();
  /**
   * <code>.BirthDateStamp birthDatestamp = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateStampOrBuilder getBirthDatestampOrBuilder();
}
