// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
