// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

/**
 * Protobuf type {@code IndividualByFioResponse}
 */
public final class IndividualByFioResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IndividualByFioResponse)
    IndividualByFioResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IndividualByFioResponse.newBuilder() to construct.
  private IndividualByFioResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IndividualByFioResponse() {
    individual_ = java.util.Collections.emptyList();
    error_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IndividualByFioResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IndividualByFioResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              individual_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio>();
              mutable_bitField0_ |= 0x00000001;
            }
            individual_.add(
                input.readMessage(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              error_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error>();
              mutable_bitField0_ |= 0x00000002;
            }
            error_.add(
                input.readMessage(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        individual_ = java.util.Collections.unmodifiableList(individual_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        error_ = java.util.Collections.unmodifiableList(error_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFioResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFioResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.Builder.class);
  }

  public static final int INDIVIDUAL_FIELD_NUMBER = 1;
  private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> individual_;
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> getIndividualList() {
    return individual_;
  }
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder> 
      getIndividualOrBuilderList() {
    return individual_;
  }
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  @java.lang.Override
  public int getIndividualCount() {
    return individual_.size();
  }
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio getIndividual(int index) {
    return individual_.get(index);
  }
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder getIndividualOrBuilder(
      int index) {
    return individual_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error> error_;
  /**
   * <code>repeated .Error error = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error> getErrorList() {
    return error_;
  }
  /**
   * <code>repeated .Error error = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder> 
      getErrorOrBuilderList() {
    return error_;
  }
  /**
   * <code>repeated .Error error = 2;</code>
   */
  @java.lang.Override
  public int getErrorCount() {
    return error_.size();
  }
  /**
   * <code>repeated .Error error = 2;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error getError(int index) {
    return error_.get(index);
  }
  /**
   * <code>repeated .Error error = 2;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder getErrorOrBuilder(
      int index) {
    return error_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < individual_.size(); i++) {
      output.writeMessage(1, individual_.get(i));
    }
    for (int i = 0; i < error_.size(); i++) {
      output.writeMessage(2, error_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < individual_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, individual_.get(i));
    }
    for (int i = 0; i < error_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, error_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse)) {
      return super.equals(obj);
    }
    com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse other = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse) obj;

    if (!getIndividualList()
        .equals(other.getIndividualList())) return false;
    if (!getErrorList()
        .equals(other.getErrorList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIndividualCount() > 0) {
      hash = (37 * hash) + INDIVIDUAL_FIELD_NUMBER;
      hash = (53 * hash) + getIndividualList().hashCode();
    }
    if (getErrorCount() > 0) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getErrorList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IndividualByFioResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IndividualByFioResponse)
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFioResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFioResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.Builder.class);
    }

    // Construct using com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIndividualFieldBuilder();
        getErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (individualBuilder_ == null) {
        individual_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        individualBuilder_.clear();
      }
      if (errorBuilder_ == null) {
        error_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        errorBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFioResponse_descriptor;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse getDefaultInstanceForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse build() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse buildPartial() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse result = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse(this);
      int from_bitField0_ = bitField0_;
      if (individualBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          individual_ = java.util.Collections.unmodifiableList(individual_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.individual_ = individual_;
      } else {
        result.individual_ = individualBuilder_.build();
      }
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          error_ = java.util.Collections.unmodifiableList(error_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse) {
        return mergeFrom((com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse other) {
      if (other == com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse.getDefaultInstance()) return this;
      if (individualBuilder_ == null) {
        if (!other.individual_.isEmpty()) {
          if (individual_.isEmpty()) {
            individual_ = other.individual_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIndividualIsMutable();
            individual_.addAll(other.individual_);
          }
          onChanged();
        }
      } else {
        if (!other.individual_.isEmpty()) {
          if (individualBuilder_.isEmpty()) {
            individualBuilder_.dispose();
            individualBuilder_ = null;
            individual_ = other.individual_;
            bitField0_ = (bitField0_ & ~0x00000001);
            individualBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIndividualFieldBuilder() : null;
          } else {
            individualBuilder_.addAllMessages(other.individual_);
          }
        }
      }
      if (errorBuilder_ == null) {
        if (!other.error_.isEmpty()) {
          if (error_.isEmpty()) {
            error_ = other.error_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureErrorIsMutable();
            error_.addAll(other.error_);
          }
          onChanged();
        }
      } else {
        if (!other.error_.isEmpty()) {
          if (errorBuilder_.isEmpty()) {
            errorBuilder_.dispose();
            errorBuilder_ = null;
            error_ = other.error_;
            bitField0_ = (bitField0_ & ~0x00000002);
            errorBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getErrorFieldBuilder() : null;
          } else {
            errorBuilder_.addAllMessages(other.error_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> individual_ =
      java.util.Collections.emptyList();
    private void ensureIndividualIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        individual_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio>(individual_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder> individualBuilder_;

    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> getIndividualList() {
      if (individualBuilder_ == null) {
        return java.util.Collections.unmodifiableList(individual_);
      } else {
        return individualBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public int getIndividualCount() {
      if (individualBuilder_ == null) {
        return individual_.size();
      } else {
        return individualBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio getIndividual(int index) {
      if (individualBuilder_ == null) {
        return individual_.get(index);
      } else {
        return individualBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder setIndividual(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio value) {
      if (individualBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndividualIsMutable();
        individual_.set(index, value);
        onChanged();
      } else {
        individualBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder setIndividual(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder builderForValue) {
      if (individualBuilder_ == null) {
        ensureIndividualIsMutable();
        individual_.set(index, builderForValue.build());
        onChanged();
      } else {
        individualBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder addIndividual(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio value) {
      if (individualBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndividualIsMutable();
        individual_.add(value);
        onChanged();
      } else {
        individualBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder addIndividual(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio value) {
      if (individualBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndividualIsMutable();
        individual_.add(index, value);
        onChanged();
      } else {
        individualBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder addIndividual(
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder builderForValue) {
      if (individualBuilder_ == null) {
        ensureIndividualIsMutable();
        individual_.add(builderForValue.build());
        onChanged();
      } else {
        individualBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder addIndividual(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder builderForValue) {
      if (individualBuilder_ == null) {
        ensureIndividualIsMutable();
        individual_.add(index, builderForValue.build());
        onChanged();
      } else {
        individualBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder addAllIndividual(
        java.lang.Iterable<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> values) {
      if (individualBuilder_ == null) {
        ensureIndividualIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, individual_);
        onChanged();
      } else {
        individualBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder clearIndividual() {
      if (individualBuilder_ == null) {
        individual_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        individualBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public Builder removeIndividual(int index) {
      if (individualBuilder_ == null) {
        ensureIndividualIsMutable();
        individual_.remove(index);
        onChanged();
      } else {
        individualBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder getIndividualBuilder(
        int index) {
      return getIndividualFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder getIndividualOrBuilder(
        int index) {
      if (individualBuilder_ == null) {
        return individual_.get(index);  } else {
        return individualBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder> 
         getIndividualOrBuilderList() {
      if (individualBuilder_ != null) {
        return individualBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(individual_);
      }
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder addIndividualBuilder() {
      return getIndividualFieldBuilder().addBuilder(
          com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.getDefaultInstance());
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder addIndividualBuilder(
        int index) {
      return getIndividualFieldBuilder().addBuilder(
          index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.getDefaultInstance());
    }
    /**
     * <code>repeated .IndividualByFio individual = 1;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder> 
         getIndividualBuilderList() {
      return getIndividualFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder> 
        getIndividualFieldBuilder() {
      if (individualBuilder_ == null) {
        individualBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder>(
                individual_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        individual_ = null;
      }
      return individualBuilder_;
    }

    private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error> error_ =
      java.util.Collections.emptyList();
    private void ensureErrorIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        error_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error>(error_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder> errorBuilder_;

    /**
     * <code>repeated .Error error = 2;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error> getErrorList() {
      if (errorBuilder_ == null) {
        return java.util.Collections.unmodifiableList(error_);
      } else {
        return errorBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public int getErrorCount() {
      if (errorBuilder_ == null) {
        return error_.size();
      } else {
        return errorBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error getError(int index) {
      if (errorBuilder_ == null) {
        return error_.get(index);
      } else {
        return errorBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder setError(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.set(index, value);
        onChanged();
      } else {
        errorBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder setError(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.set(index, builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder addError(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.add(value);
        onChanged();
      } else {
        errorBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder addError(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.add(index, value);
        onChanged();
      } else {
        errorBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder addError(
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.add(builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder addError(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.add(index, builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder addAllError(
        java.lang.Iterable<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error> values) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, error_);
        onChanged();
      } else {
        errorBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public Builder removeError(int index) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.remove(index);
        onChanged();
      } else {
        errorBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder getErrorBuilder(
        int index) {
      return getErrorFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder getErrorOrBuilder(
        int index) {
      if (errorBuilder_ == null) {
        return error_.get(index);  } else {
        return errorBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder> 
         getErrorOrBuilderList() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(error_);
      }
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder addErrorBuilder() {
      return getErrorFieldBuilder().addBuilder(
          com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.getDefaultInstance());
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder addErrorBuilder(
        int index) {
      return getErrorFieldBuilder().addBuilder(
          index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.getDefaultInstance());
    }
    /**
     * <code>repeated .Error error = 2;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder> 
         getErrorBuilderList() {
      return getErrorFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Error.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.ErrorOrBuilder>(
                error_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IndividualByFioResponse)
  }

  // @@protoc_insertion_point(class_scope:IndividualByFioResponse)
  private static final com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse();
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IndividualByFioResponse>
      PARSER = new com.google.protobuf.AbstractParser<IndividualByFioResponse>() {
    @java.lang.Override
    public IndividualByFioResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IndividualByFioResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IndividualByFioResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IndividualByFioResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

