// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface IndividualByFResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndividualByFResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .IndividualByF individual = 1;</code>
   */
  java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByF> 
      getIndividualList();
  /**
   * <code>repeated .IndividualByF individual = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByF getIndividual(int index);
  /**
   * <code>repeated .IndividualByF individual = 1;</code>
   */
  int getIndividualCount();
  /**
   * <code>repeated .IndividualByF individual = 1;</code>
   */
  java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFOrBuilder> 
      getIndividualOrBuilderList();
  /**
   * <code>repeated .IndividualByF individual = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFOrBuilder getIndividualOrBuilder(
      int index);
}
