// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

/**
 * Protobuf type {@code IndividualByFRequest}
 */
public final class IndividualByFRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IndividualByFRequest)
    IndividualByFRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IndividualByFRequest.newBuilder() to construct.
  private IndividualByFRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IndividualByFRequest() {
    surname_ = "";
    segment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IndividualByFRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IndividualByFRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            surname_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            segment_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.Builder.class);
  }

  public static final int SURNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object surname_;
  /**
   * <code>string surname = 1;</code>
   * @return The surname.
   */
  @java.lang.Override
  public java.lang.String getSurname() {
    java.lang.Object ref = surname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      surname_ = s;
      return s;
    }
  }
  /**
   * <code>string surname = 1;</code>
   * @return The bytes for surname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSurnameBytes() {
    java.lang.Object ref = surname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      surname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object segment_;
  /**
   * <code>string segment = 2;</code>
   * @return The segment.
   */
  @java.lang.Override
  public java.lang.String getSegment() {
    java.lang.Object ref = segment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      segment_ = s;
      return s;
    }
  }
  /**
   * <code>string segment = 2;</code>
   * @return The bytes for segment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSegmentBytes() {
    java.lang.Object ref = segment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      segment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSurnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, surname_);
    }
    if (!getSegmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, segment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSurnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, surname_);
    }
    if (!getSegmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, segment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest)) {
      return super.equals(obj);
    }
    com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest other = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest) obj;

    if (!getSurname()
        .equals(other.getSurname())) return false;
    if (!getSegment()
        .equals(other.getSegment())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SURNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSurname().hashCode();
    hash = (37 * hash) + SEGMENT_FIELD_NUMBER;
    hash = (53 * hash) + getSegment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IndividualByFRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IndividualByFRequest)
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.Builder.class);
    }

    // Construct using com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      surname_ = "";

      segment_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_IndividualByFRequest_descriptor;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest getDefaultInstanceForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest build() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest buildPartial() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest result = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest(this);
      result.surname_ = surname_;
      result.segment_ = segment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest) {
        return mergeFrom((com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest other) {
      if (other == com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest.getDefaultInstance()) return this;
      if (!other.getSurname().isEmpty()) {
        surname_ = other.surname_;
        onChanged();
      }
      if (!other.getSegment().isEmpty()) {
        segment_ = other.segment_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object surname_ = "";
    /**
     * <code>string surname = 1;</code>
     * @return The surname.
     */
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string surname = 1;</code>
     * @return The bytes for surname.
     */
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string surname = 1;</code>
     * @param value The surname to set.
     * @return This builder for chaining.
     */
    public Builder setSurname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      surname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string surname = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSurname() {
      
      surname_ = getDefaultInstance().getSurname();
      onChanged();
      return this;
    }
    /**
     * <code>string surname = 1;</code>
     * @param value The bytes for surname to set.
     * @return This builder for chaining.
     */
    public Builder setSurnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      surname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object segment_ = "";
    /**
     * <code>string segment = 2;</code>
     * @return The segment.
     */
    public java.lang.String getSegment() {
      java.lang.Object ref = segment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        segment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string segment = 2;</code>
     * @return The bytes for segment.
     */
    public com.google.protobuf.ByteString
        getSegmentBytes() {
      java.lang.Object ref = segment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        segment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string segment = 2;</code>
     * @param value The segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      segment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string segment = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegment() {
      
      segment_ = getDefaultInstance().getSegment();
      onChanged();
      return this;
    }
    /**
     * <code>string segment = 2;</code>
     * @param value The bytes for segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      segment_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IndividualByFRequest)
  }

  // @@protoc_insertion_point(class_scope:IndividualByFRequest)
  private static final com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest();
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IndividualByFRequest>
      PARSER = new com.google.protobuf.AbstractParser<IndividualByFRequest>() {
    @java.lang.Override
    public IndividualByFRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IndividualByFRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IndividualByFRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IndividualByFRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

