// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface IndividualByFioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndividualByFio)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Name individualName = 3;</code>
   * @return Whether the individualName field is set.
   */
  boolean hasIndividualName();
  /**
   * <code>.Name individualName = 3;</code>
   * @return The individualName.
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.Name getIndividualName();
  /**
   * <code>.Name individualName = 3;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.NameOrBuilder getIndividualNameOrBuilder();

  /**
   * <code>.BirthDate birthDate = 4;</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>.BirthDate birthDate = 4;</code>
   * @return The birthDate.
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDate getBirthDate();
  /**
   * <code>.BirthDate birthDate = 4;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.BirthDateOrBuilder getBirthDateOrBuilder();

  /**
   * <code>.PartyGroups partyGroups = 5;</code>
   * @return Whether the partyGroups field is set.
   */
  boolean hasPartyGroups();
  /**
   * <code>.PartyGroups partyGroups = 5;</code>
   * @return The partyGroups.
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups getPartyGroups();
  /**
   * <code>.PartyGroups partyGroups = 5;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupsOrBuilder getPartyGroupsOrBuilder();

  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio.OptionalCase getOptionalCase();
}
