// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface IndividualByFioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndividualByFioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 2;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 2;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>string patronymic = 3;</code>
   * @return The patronymic.
   */
  java.lang.String getPatronymic();
  /**
   * <code>string patronymic = 3;</code>
   * @return The bytes for patronymic.
   */
  com.google.protobuf.ByteString
      getPatronymicBytes();

  /**
   * <code>string segment = 4;</code>
   * @return The segment.
   */
  java.lang.String getSegment();
  /**
   * <code>string segment = 4;</code>
   * @return The bytes for segment.
   */
  com.google.protobuf.ByteString
      getSegmentBytes();
}
