// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface IndividualByFRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndividualByFRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string surname = 1;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 1;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>string segment = 2;</code>
   * @return The segment.
   */
  java.lang.String getSegment();
  /**
   * <code>string segment = 2;</code>
   * @return The bytes for segment.
   */
  com.google.protobuf.ByteString
      getSegmentBytes();
}
