// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface IndividualByFioResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndividualByFioResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio> 
      getIndividualList();
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFio getIndividual(int index);
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  int getIndividualCount();
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder> 
      getIndividualOrBuilderList();
  /**
   * <code>repeated .IndividualByFio individual = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.IndividualByFioOrBuilder getIndividualOrBuilder(
      int index);
}
