// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public final class MethodSearchByF {
  private MethodSearchByF() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BirthDateStamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BirthDateStamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BirthDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BirthDate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByF_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByF_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFioResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFioResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025methodSearchByF.proto\"E\n\004Name\022\n\n\002id\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007surname\030\003 \001(\t\022\022\n\npa" +
      "tronymic\030\004 \001(\t\":\n\016BirthDateStamp\022\013\n\003day\030" +
      "\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004year\030\003 \001(\005\"4\n\tBi" +
      "rthDate\022\'\n\016birthDatestamp\030\001 \001(\0132\017.BirthD" +
      "ateStamp\"j\n\rIndividualByF\022\n\n\002id\030\001 \001(\t\022\017\n" +
      "\007version\030\002 \001(\005\022\035\n\016individualName\030\003 \001(\0132\005" +
      ".Name\022\035\n\tbirthDate\030\004 \001(\0132\n.BirthDate\"8\n\024" +
      "IndividualByFRequest\022\017\n\007surname\030\001 \001(\t\022\017\n" +
      "\007segment\030\002 \001(\t\";\n\025IndividualByFResponse\022" +
      "\"\n\nindividual\030\001 \003(\0132\016.IndividualByF\"\\\n\026I" +
      "ndividualByFioRequest\022\014\n\004name\030\001 \001(\t\022\017\n\007s" +
      "urname\030\002 \001(\t\022\022\n\npatronymic\030\003 \001(\t\022\017\n\007segm" +
      "ent\030\004 \001(\t\"?\n\027IndividualByFioResponse\022$\n\n" +
      "individual\030\001 \003(\0132\020.IndividualByFio\"l\n\017In" +
      "dividualByFio\022\n\n\002id\030\001 \001(\t\022\017\n\007version\030\002 \001" +
      "(\005\022\035\n\016individualName\030\003 \001(\0132\005.Name\022\035\n\tbir" +
      "thDate\030\004 \001(\0132\n.BirthDate2\252\001\n*AbcPrivateB" +
      "ankingChatxSearchGatewayService\022:\n\tSearc" +
      "hByF\022\025.IndividualByFRequest\032\026.Individual" +
      "ByFResponse\022@\n\013SearchByFio\022\027.IndividualB" +
      "yFioRequest\032\030.IndividualByFioResponseB<\n" +
      "8com.stub.stub_Rest_gRPC.serviceGRPC.ser" +
      "viceSearchByF_FioP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Name_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Name_descriptor,
        new java.lang.String[] { "Id", "Name", "Surname", "Patronymic", });
    internal_static_BirthDateStamp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BirthDateStamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BirthDateStamp_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", });
    internal_static_BirthDate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BirthDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BirthDate_descriptor,
        new java.lang.String[] { "BirthDatestamp", });
    internal_static_IndividualByF_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_IndividualByF_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByF_descriptor,
        new java.lang.String[] { "Id", "Version", "IndividualName", "BirthDate", });
    internal_static_IndividualByFRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_IndividualByFRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFRequest_descriptor,
        new java.lang.String[] { "Surname", "Segment", });
    internal_static_IndividualByFResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_IndividualByFResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFResponse_descriptor,
        new java.lang.String[] { "Individual", });
    internal_static_IndividualByFioRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_IndividualByFioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFioRequest_descriptor,
        new java.lang.String[] { "Name", "Surname", "Patronymic", "Segment", });
    internal_static_IndividualByFioResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_IndividualByFioResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFioResponse_descriptor,
        new java.lang.String[] { "Individual", });
    internal_static_IndividualByFio_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_IndividualByFio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFio_descriptor,
        new java.lang.String[] { "Id", "Version", "IndividualName", "BirthDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
