// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public final class MethodSearchByF {
  private MethodSearchByF() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BirthDateStamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BirthDateStamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BirthDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BirthDate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartyGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyGroups_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartyGroups_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByF_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByF_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndividualByFioResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndividualByFioResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025methodSearchByF.proto\"E\n\004Name\022\n\n\002id\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007surname\030\003 \001(\t\022\022\n\npa" +
      "tronymic\030\004 \001(\t\":\n\016BirthDateStamp\022\013\n\003day\030" +
      "\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004year\030\003 \001(\005\"4\n\tBi" +
      "rthDate\022\'\n\016birthDatestamp\030\001 \001(\0132\017.BirthD" +
      "ateStamp\"(\n\nPartyGroup\022\032\n\022partyGroupDict" +
      "Code\030\001 \001(\t\"\236\002\n\013PartyGroups\022\"\n\rtoPartyGro" +
      "ups\030\001 \003(\0132\013.PartyGroup\022\033\n\023accessibilityG" +
      "roups\030\002 \001(\t\022\026\n\016highRiskGroups\030\003 \001(\t\022\037\n\027i" +
      "ncreasedInterestGroups\030\004 \001(\t\022\031\n\021insiderI" +
      "nfoGroups\030\005 \001(\t\022\032\n\022investorInfoGroups\030\006 " +
      "\001(\t\022\021\n\tpfrGroups\030\007 \001(\t\022\025\n\rproductGroups\030" +
      "\010 \001(\t\022\037\n\027vipClientCategoryGroups\030\t \001(\t\022\023" +
      "\n\013visionGroup\030\n \001(\t\"\030\n\005Error\022\017\n\007message\030" +
      "\001 \001(\t\"\233\001\n\rIndividualByF\022\n\n\002id\030\001 \001(\t\022\017\n\007v" +
      "ersion\030\002 \001(\005\022\035\n\016individualName\030\003 \001(\0132\005.N" +
      "ame\022\035\n\tbirthDate\030\004 \001(\0132\n.BirthDate\022#\n\013pa" +
      "rtyGroups\030\005 \001(\0132\014.PartyGroupsH\000B\n\n\010optio" +
      "nal\"8\n\024IndividualByFRequest\022\017\n\007surname\030\001" +
      " \001(\t\022\017\n\007segment\030\002 \001(\t\"R\n\025IndividualByFRe" +
      "sponse\022\"\n\nindividual\030\001 \003(\0132\016.IndividualB" +
      "yF\022\025\n\005error\030\002 \003(\0132\006.Error\"\235\001\n\017Individual" +
      "ByFio\022\n\n\002id\030\001 \001(\t\022\017\n\007version\030\002 \001(\005\022\035\n\016in" +
      "dividualName\030\003 \001(\0132\005.Name\022\035\n\tbirthDate\030\004" +
      " \001(\0132\n.BirthDate\022#\n\013partyGroups\030\005 \001(\0132\014." +
      "PartyGroupsH\000B\n\n\010optional\"\\\n\026IndividualB" +
      "yFioRequest\022\014\n\004name\030\001 \001(\t\022\017\n\007surname\030\002 \001" +
      "(\t\022\022\n\npatronymic\030\003 \001(\t\022\017\n\007segment\030\004 \001(\t\"" +
      "V\n\027IndividualByFioResponse\022$\n\nindividual" +
      "\030\001 \003(\0132\020.IndividualByFio\022\025\n\005error\030\002 \003(\0132" +
      "\006.Error2\252\001\n*AbcPrivateBankingChatxSearch" +
      "GatewayService\022:\n\tSearchByF\022\025.Individual" +
      "ByFRequest\032\026.IndividualByFResponse\022@\n\013Se" +
      "archByFio\022\027.IndividualByFioRequest\032\030.Ind" +
      "ividualByFioResponseB<\n8com.stub.stub_Re" +
      "st_gRPC.serviceGRPC.serviceSearchByF_Fio" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Name_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Name_descriptor,
        new java.lang.String[] { "Id", "Name", "Surname", "Patronymic", });
    internal_static_BirthDateStamp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BirthDateStamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BirthDateStamp_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", });
    internal_static_BirthDate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BirthDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BirthDate_descriptor,
        new java.lang.String[] { "BirthDatestamp", });
    internal_static_PartyGroup_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PartyGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartyGroup_descriptor,
        new java.lang.String[] { "PartyGroupDictCode", });
    internal_static_PartyGroups_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PartyGroups_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartyGroups_descriptor,
        new java.lang.String[] { "ToPartyGroups", "AccessibilityGroups", "HighRiskGroups", "IncreasedInterestGroups", "InsiderInfoGroups", "InvestorInfoGroups", "PfrGroups", "ProductGroups", "VipClientCategoryGroups", "VisionGroup", });
    internal_static_Error_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Error_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_IndividualByF_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_IndividualByF_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByF_descriptor,
        new java.lang.String[] { "Id", "Version", "IndividualName", "BirthDate", "PartyGroups", "Optional", });
    internal_static_IndividualByFRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_IndividualByFRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFRequest_descriptor,
        new java.lang.String[] { "Surname", "Segment", });
    internal_static_IndividualByFResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_IndividualByFResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFResponse_descriptor,
        new java.lang.String[] { "Individual", "Error", });
    internal_static_IndividualByFio_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_IndividualByFio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFio_descriptor,
        new java.lang.String[] { "Id", "Version", "IndividualName", "BirthDate", "PartyGroups", "Optional", });
    internal_static_IndividualByFioRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_IndividualByFioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFioRequest_descriptor,
        new java.lang.String[] { "Name", "Surname", "Patronymic", "Segment", });
    internal_static_IndividualByFioResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_IndividualByFioResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndividualByFioResponse_descriptor,
        new java.lang.String[] { "Individual", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
