// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface PartyGroupsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PartyGroups)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> 
      getToPartyGroupsList();
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getToPartyGroups(int index);
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  int getToPartyGroupsCount();
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder> 
      getToPartyGroupsOrBuilderList();
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder getToPartyGroupsOrBuilder(
      int index);

  /**
   * <code>string accessibilityGroups = 2;</code>
   * @return The accessibilityGroups.
   */
  java.lang.String getAccessibilityGroups();
  /**
   * <code>string accessibilityGroups = 2;</code>
   * @return The bytes for accessibilityGroups.
   */
  com.google.protobuf.ByteString
      getAccessibilityGroupsBytes();

  /**
   * <code>string highRiskGroups = 3;</code>
   * @return The highRiskGroups.
   */
  java.lang.String getHighRiskGroups();
  /**
   * <code>string highRiskGroups = 3;</code>
   * @return The bytes for highRiskGroups.
   */
  com.google.protobuf.ByteString
      getHighRiskGroupsBytes();

  /**
   * <code>string increasedInterestGroups = 4;</code>
   * @return The increasedInterestGroups.
   */
  java.lang.String getIncreasedInterestGroups();
  /**
   * <code>string increasedInterestGroups = 4;</code>
   * @return The bytes for increasedInterestGroups.
   */
  com.google.protobuf.ByteString
      getIncreasedInterestGroupsBytes();

  /**
   * <code>string insiderInfoGroups = 5;</code>
   * @return The insiderInfoGroups.
   */
  java.lang.String getInsiderInfoGroups();
  /**
   * <code>string insiderInfoGroups = 5;</code>
   * @return The bytes for insiderInfoGroups.
   */
  com.google.protobuf.ByteString
      getInsiderInfoGroupsBytes();

  /**
   * <code>string investorInfoGroups = 6;</code>
   * @return The investorInfoGroups.
   */
  java.lang.String getInvestorInfoGroups();
  /**
   * <code>string investorInfoGroups = 6;</code>
   * @return The bytes for investorInfoGroups.
   */
  com.google.protobuf.ByteString
      getInvestorInfoGroupsBytes();

  /**
   * <code>string pfrGroups = 7;</code>
   * @return The pfrGroups.
   */
  java.lang.String getPfrGroups();
  /**
   * <code>string pfrGroups = 7;</code>
   * @return The bytes for pfrGroups.
   */
  com.google.protobuf.ByteString
      getPfrGroupsBytes();

  /**
   * <code>string productGroups = 8;</code>
   * @return The productGroups.
   */
  java.lang.String getProductGroups();
  /**
   * <code>string productGroups = 8;</code>
   * @return The bytes for productGroups.
   */
  com.google.protobuf.ByteString
      getProductGroupsBytes();

  /**
   * <code>string vipClientCategoryGroups = 9;</code>
   * @return The vipClientCategoryGroups.
   */
  java.lang.String getVipClientCategoryGroups();
  /**
   * <code>string vipClientCategoryGroups = 9;</code>
   * @return The bytes for vipClientCategoryGroups.
   */
  com.google.protobuf.ByteString
      getVipClientCategoryGroupsBytes();

  /**
   * <code>string visionGroup = 10;</code>
   * @return The visionGroup.
   */
  java.lang.String getVisionGroup();
  /**
   * <code>string visionGroup = 10;</code>
   * @return The bytes for visionGroup.
   */
  com.google.protobuf.ByteString
      getVisionGroupBytes();
}
