// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

/**
 * Protobuf type {@code PartyGroups}
 */
public final class PartyGroups extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PartyGroups)
    PartyGroupsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartyGroups.newBuilder() to construct.
  private PartyGroups(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartyGroups() {
    toPartyGroups_ = java.util.Collections.emptyList();
    accessibilityGroups_ = "";
    highRiskGroups_ = "";
    increasedInterestGroups_ = "";
    insiderInfoGroups_ = "";
    investorInfoGroups_ = "";
    pfrGroups_ = "";
    productGroups_ = "";
    vipClientCategoryGroups_ = "";
    visionGroup_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartyGroups();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartyGroups(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              toPartyGroups_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup>();
              mutable_bitField0_ |= 0x00000001;
            }
            toPartyGroups_.add(
                input.readMessage(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            accessibilityGroups_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            highRiskGroups_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            increasedInterestGroups_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            insiderInfoGroups_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            investorInfoGroups_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            pfrGroups_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            productGroups_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            vipClientCategoryGroups_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            visionGroup_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        toPartyGroups_ = java.util.Collections.unmodifiableList(toPartyGroups_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroups_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroups_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.Builder.class);
  }

  public static final int TOPARTYGROUPS_FIELD_NUMBER = 1;
  private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> toPartyGroups_;
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> getToPartyGroupsList() {
    return toPartyGroups_;
  }
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder> 
      getToPartyGroupsOrBuilderList() {
    return toPartyGroups_;
  }
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  @java.lang.Override
  public int getToPartyGroupsCount() {
    return toPartyGroups_.size();
  }
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getToPartyGroups(int index) {
    return toPartyGroups_.get(index);
  }
  /**
   * <code>repeated .PartyGroup toPartyGroups = 1;</code>
   */
  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder getToPartyGroupsOrBuilder(
      int index) {
    return toPartyGroups_.get(index);
  }

  public static final int ACCESSIBILITYGROUPS_FIELD_NUMBER = 2;
  private volatile java.lang.Object accessibilityGroups_;
  /**
   * <code>string accessibilityGroups = 2;</code>
   * @return The accessibilityGroups.
   */
  @java.lang.Override
  public java.lang.String getAccessibilityGroups() {
    java.lang.Object ref = accessibilityGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessibilityGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string accessibilityGroups = 2;</code>
   * @return The bytes for accessibilityGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessibilityGroupsBytes() {
    java.lang.Object ref = accessibilityGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessibilityGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGHRISKGROUPS_FIELD_NUMBER = 3;
  private volatile java.lang.Object highRiskGroups_;
  /**
   * <code>string highRiskGroups = 3;</code>
   * @return The highRiskGroups.
   */
  @java.lang.Override
  public java.lang.String getHighRiskGroups() {
    java.lang.Object ref = highRiskGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      highRiskGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string highRiskGroups = 3;</code>
   * @return The bytes for highRiskGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHighRiskGroupsBytes() {
    java.lang.Object ref = highRiskGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      highRiskGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCREASEDINTERESTGROUPS_FIELD_NUMBER = 4;
  private volatile java.lang.Object increasedInterestGroups_;
  /**
   * <code>string increasedInterestGroups = 4;</code>
   * @return The increasedInterestGroups.
   */
  @java.lang.Override
  public java.lang.String getIncreasedInterestGroups() {
    java.lang.Object ref = increasedInterestGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      increasedInterestGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string increasedInterestGroups = 4;</code>
   * @return The bytes for increasedInterestGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIncreasedInterestGroupsBytes() {
    java.lang.Object ref = increasedInterestGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      increasedInterestGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSIDERINFOGROUPS_FIELD_NUMBER = 5;
  private volatile java.lang.Object insiderInfoGroups_;
  /**
   * <code>string insiderInfoGroups = 5;</code>
   * @return The insiderInfoGroups.
   */
  @java.lang.Override
  public java.lang.String getInsiderInfoGroups() {
    java.lang.Object ref = insiderInfoGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      insiderInfoGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string insiderInfoGroups = 5;</code>
   * @return The bytes for insiderInfoGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInsiderInfoGroupsBytes() {
    java.lang.Object ref = insiderInfoGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      insiderInfoGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVESTORINFOGROUPS_FIELD_NUMBER = 6;
  private volatile java.lang.Object investorInfoGroups_;
  /**
   * <code>string investorInfoGroups = 6;</code>
   * @return The investorInfoGroups.
   */
  @java.lang.Override
  public java.lang.String getInvestorInfoGroups() {
    java.lang.Object ref = investorInfoGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      investorInfoGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string investorInfoGroups = 6;</code>
   * @return The bytes for investorInfoGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvestorInfoGroupsBytes() {
    java.lang.Object ref = investorInfoGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      investorInfoGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PFRGROUPS_FIELD_NUMBER = 7;
  private volatile java.lang.Object pfrGroups_;
  /**
   * <code>string pfrGroups = 7;</code>
   * @return The pfrGroups.
   */
  @java.lang.Override
  public java.lang.String getPfrGroups() {
    java.lang.Object ref = pfrGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pfrGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string pfrGroups = 7;</code>
   * @return The bytes for pfrGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPfrGroupsBytes() {
    java.lang.Object ref = pfrGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pfrGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTGROUPS_FIELD_NUMBER = 8;
  private volatile java.lang.Object productGroups_;
  /**
   * <code>string productGroups = 8;</code>
   * @return The productGroups.
   */
  @java.lang.Override
  public java.lang.String getProductGroups() {
    java.lang.Object ref = productGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string productGroups = 8;</code>
   * @return The bytes for productGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductGroupsBytes() {
    java.lang.Object ref = productGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIPCLIENTCATEGORYGROUPS_FIELD_NUMBER = 9;
  private volatile java.lang.Object vipClientCategoryGroups_;
  /**
   * <code>string vipClientCategoryGroups = 9;</code>
   * @return The vipClientCategoryGroups.
   */
  @java.lang.Override
  public java.lang.String getVipClientCategoryGroups() {
    java.lang.Object ref = vipClientCategoryGroups_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vipClientCategoryGroups_ = s;
      return s;
    }
  }
  /**
   * <code>string vipClientCategoryGroups = 9;</code>
   * @return The bytes for vipClientCategoryGroups.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVipClientCategoryGroupsBytes() {
    java.lang.Object ref = vipClientCategoryGroups_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vipClientCategoryGroups_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VISIONGROUP_FIELD_NUMBER = 10;
  private volatile java.lang.Object visionGroup_;
  /**
   * <code>string visionGroup = 10;</code>
   * @return The visionGroup.
   */
  @java.lang.Override
  public java.lang.String getVisionGroup() {
    java.lang.Object ref = visionGroup_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      visionGroup_ = s;
      return s;
    }
  }
  /**
   * <code>string visionGroup = 10;</code>
   * @return The bytes for visionGroup.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVisionGroupBytes() {
    java.lang.Object ref = visionGroup_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      visionGroup_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < toPartyGroups_.size(); i++) {
      output.writeMessage(1, toPartyGroups_.get(i));
    }
    if (!getAccessibilityGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accessibilityGroups_);
    }
    if (!getHighRiskGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, highRiskGroups_);
    }
    if (!getIncreasedInterestGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, increasedInterestGroups_);
    }
    if (!getInsiderInfoGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, insiderInfoGroups_);
    }
    if (!getInvestorInfoGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, investorInfoGroups_);
    }
    if (!getPfrGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pfrGroups_);
    }
    if (!getProductGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, productGroups_);
    }
    if (!getVipClientCategoryGroupsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, vipClientCategoryGroups_);
    }
    if (!getVisionGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, visionGroup_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < toPartyGroups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, toPartyGroups_.get(i));
    }
    if (!getAccessibilityGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accessibilityGroups_);
    }
    if (!getHighRiskGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, highRiskGroups_);
    }
    if (!getIncreasedInterestGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, increasedInterestGroups_);
    }
    if (!getInsiderInfoGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, insiderInfoGroups_);
    }
    if (!getInvestorInfoGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, investorInfoGroups_);
    }
    if (!getPfrGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pfrGroups_);
    }
    if (!getProductGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, productGroups_);
    }
    if (!getVipClientCategoryGroupsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, vipClientCategoryGroups_);
    }
    if (!getVisionGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, visionGroup_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups)) {
      return super.equals(obj);
    }
    com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups other = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups) obj;

    if (!getToPartyGroupsList()
        .equals(other.getToPartyGroupsList())) return false;
    if (!getAccessibilityGroups()
        .equals(other.getAccessibilityGroups())) return false;
    if (!getHighRiskGroups()
        .equals(other.getHighRiskGroups())) return false;
    if (!getIncreasedInterestGroups()
        .equals(other.getIncreasedInterestGroups())) return false;
    if (!getInsiderInfoGroups()
        .equals(other.getInsiderInfoGroups())) return false;
    if (!getInvestorInfoGroups()
        .equals(other.getInvestorInfoGroups())) return false;
    if (!getPfrGroups()
        .equals(other.getPfrGroups())) return false;
    if (!getProductGroups()
        .equals(other.getProductGroups())) return false;
    if (!getVipClientCategoryGroups()
        .equals(other.getVipClientCategoryGroups())) return false;
    if (!getVisionGroup()
        .equals(other.getVisionGroup())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getToPartyGroupsCount() > 0) {
      hash = (37 * hash) + TOPARTYGROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getToPartyGroupsList().hashCode();
    }
    hash = (37 * hash) + ACCESSIBILITYGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getAccessibilityGroups().hashCode();
    hash = (37 * hash) + HIGHRISKGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getHighRiskGroups().hashCode();
    hash = (37 * hash) + INCREASEDINTERESTGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getIncreasedInterestGroups().hashCode();
    hash = (37 * hash) + INSIDERINFOGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getInsiderInfoGroups().hashCode();
    hash = (37 * hash) + INVESTORINFOGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getInvestorInfoGroups().hashCode();
    hash = (37 * hash) + PFRGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getPfrGroups().hashCode();
    hash = (37 * hash) + PRODUCTGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getProductGroups().hashCode();
    hash = (37 * hash) + VIPCLIENTCATEGORYGROUPS_FIELD_NUMBER;
    hash = (53 * hash) + getVipClientCategoryGroups().hashCode();
    hash = (37 * hash) + VISIONGROUP_FIELD_NUMBER;
    hash = (53 * hash) + getVisionGroup().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PartyGroups}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PartyGroups)
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroups_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroups_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.Builder.class);
    }

    // Construct using com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getToPartyGroupsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (toPartyGroupsBuilder_ == null) {
        toPartyGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        toPartyGroupsBuilder_.clear();
      }
      accessibilityGroups_ = "";

      highRiskGroups_ = "";

      increasedInterestGroups_ = "";

      insiderInfoGroups_ = "";

      investorInfoGroups_ = "";

      pfrGroups_ = "";

      productGroups_ = "";

      vipClientCategoryGroups_ = "";

      visionGroup_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroups_descriptor;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups getDefaultInstanceForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.getDefaultInstance();
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups build() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups buildPartial() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups result = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups(this);
      int from_bitField0_ = bitField0_;
      if (toPartyGroupsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          toPartyGroups_ = java.util.Collections.unmodifiableList(toPartyGroups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.toPartyGroups_ = toPartyGroups_;
      } else {
        result.toPartyGroups_ = toPartyGroupsBuilder_.build();
      }
      result.accessibilityGroups_ = accessibilityGroups_;
      result.highRiskGroups_ = highRiskGroups_;
      result.increasedInterestGroups_ = increasedInterestGroups_;
      result.insiderInfoGroups_ = insiderInfoGroups_;
      result.investorInfoGroups_ = investorInfoGroups_;
      result.pfrGroups_ = pfrGroups_;
      result.productGroups_ = productGroups_;
      result.vipClientCategoryGroups_ = vipClientCategoryGroups_;
      result.visionGroup_ = visionGroup_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups) {
        return mergeFrom((com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups other) {
      if (other == com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups.getDefaultInstance()) return this;
      if (toPartyGroupsBuilder_ == null) {
        if (!other.toPartyGroups_.isEmpty()) {
          if (toPartyGroups_.isEmpty()) {
            toPartyGroups_ = other.toPartyGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToPartyGroupsIsMutable();
            toPartyGroups_.addAll(other.toPartyGroups_);
          }
          onChanged();
        }
      } else {
        if (!other.toPartyGroups_.isEmpty()) {
          if (toPartyGroupsBuilder_.isEmpty()) {
            toPartyGroupsBuilder_.dispose();
            toPartyGroupsBuilder_ = null;
            toPartyGroups_ = other.toPartyGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
            toPartyGroupsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getToPartyGroupsFieldBuilder() : null;
          } else {
            toPartyGroupsBuilder_.addAllMessages(other.toPartyGroups_);
          }
        }
      }
      if (!other.getAccessibilityGroups().isEmpty()) {
        accessibilityGroups_ = other.accessibilityGroups_;
        onChanged();
      }
      if (!other.getHighRiskGroups().isEmpty()) {
        highRiskGroups_ = other.highRiskGroups_;
        onChanged();
      }
      if (!other.getIncreasedInterestGroups().isEmpty()) {
        increasedInterestGroups_ = other.increasedInterestGroups_;
        onChanged();
      }
      if (!other.getInsiderInfoGroups().isEmpty()) {
        insiderInfoGroups_ = other.insiderInfoGroups_;
        onChanged();
      }
      if (!other.getInvestorInfoGroups().isEmpty()) {
        investorInfoGroups_ = other.investorInfoGroups_;
        onChanged();
      }
      if (!other.getPfrGroups().isEmpty()) {
        pfrGroups_ = other.pfrGroups_;
        onChanged();
      }
      if (!other.getProductGroups().isEmpty()) {
        productGroups_ = other.productGroups_;
        onChanged();
      }
      if (!other.getVipClientCategoryGroups().isEmpty()) {
        vipClientCategoryGroups_ = other.vipClientCategoryGroups_;
        onChanged();
      }
      if (!other.getVisionGroup().isEmpty()) {
        visionGroup_ = other.visionGroup_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> toPartyGroups_ =
      java.util.Collections.emptyList();
    private void ensureToPartyGroupsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        toPartyGroups_ = new java.util.ArrayList<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup>(toPartyGroups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder> toPartyGroupsBuilder_;

    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> getToPartyGroupsList() {
      if (toPartyGroupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(toPartyGroups_);
      } else {
        return toPartyGroupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public int getToPartyGroupsCount() {
      if (toPartyGroupsBuilder_ == null) {
        return toPartyGroups_.size();
      } else {
        return toPartyGroupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getToPartyGroups(int index) {
      if (toPartyGroupsBuilder_ == null) {
        return toPartyGroups_.get(index);
      } else {
        return toPartyGroupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder setToPartyGroups(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup value) {
      if (toPartyGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.set(index, value);
        onChanged();
      } else {
        toPartyGroupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder setToPartyGroups(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder builderForValue) {
      if (toPartyGroupsBuilder_ == null) {
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.set(index, builderForValue.build());
        onChanged();
      } else {
        toPartyGroupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder addToPartyGroups(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup value) {
      if (toPartyGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.add(value);
        onChanged();
      } else {
        toPartyGroupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder addToPartyGroups(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup value) {
      if (toPartyGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.add(index, value);
        onChanged();
      } else {
        toPartyGroupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder addToPartyGroups(
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder builderForValue) {
      if (toPartyGroupsBuilder_ == null) {
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.add(builderForValue.build());
        onChanged();
      } else {
        toPartyGroupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder addToPartyGroups(
        int index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder builderForValue) {
      if (toPartyGroupsBuilder_ == null) {
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.add(index, builderForValue.build());
        onChanged();
      } else {
        toPartyGroupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder addAllToPartyGroups(
        java.lang.Iterable<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup> values) {
      if (toPartyGroupsBuilder_ == null) {
        ensureToPartyGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toPartyGroups_);
        onChanged();
      } else {
        toPartyGroupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder clearToPartyGroups() {
      if (toPartyGroupsBuilder_ == null) {
        toPartyGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        toPartyGroupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public Builder removeToPartyGroups(int index) {
      if (toPartyGroupsBuilder_ == null) {
        ensureToPartyGroupsIsMutable();
        toPartyGroups_.remove(index);
        onChanged();
      } else {
        toPartyGroupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder getToPartyGroupsBuilder(
        int index) {
      return getToPartyGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder getToPartyGroupsOrBuilder(
        int index) {
      if (toPartyGroupsBuilder_ == null) {
        return toPartyGroups_.get(index);  } else {
        return toPartyGroupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public java.util.List<? extends com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder> 
         getToPartyGroupsOrBuilderList() {
      if (toPartyGroupsBuilder_ != null) {
        return toPartyGroupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(toPartyGroups_);
      }
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder addToPartyGroupsBuilder() {
      return getToPartyGroupsFieldBuilder().addBuilder(
          com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder addToPartyGroupsBuilder(
        int index) {
      return getToPartyGroupsFieldBuilder().addBuilder(
          index, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .PartyGroup toPartyGroups = 1;</code>
     */
    public java.util.List<com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder> 
         getToPartyGroupsBuilderList() {
      return getToPartyGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder> 
        getToPartyGroupsFieldBuilder() {
      if (toPartyGroupsBuilder_ == null) {
        toPartyGroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder>(
                toPartyGroups_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        toPartyGroups_ = null;
      }
      return toPartyGroupsBuilder_;
    }

    private java.lang.Object accessibilityGroups_ = "";
    /**
     * <code>string accessibilityGroups = 2;</code>
     * @return The accessibilityGroups.
     */
    public java.lang.String getAccessibilityGroups() {
      java.lang.Object ref = accessibilityGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessibilityGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accessibilityGroups = 2;</code>
     * @return The bytes for accessibilityGroups.
     */
    public com.google.protobuf.ByteString
        getAccessibilityGroupsBytes() {
      java.lang.Object ref = accessibilityGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessibilityGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accessibilityGroups = 2;</code>
     * @param value The accessibilityGroups to set.
     * @return This builder for chaining.
     */
    public Builder setAccessibilityGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessibilityGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accessibilityGroups = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessibilityGroups() {
      
      accessibilityGroups_ = getDefaultInstance().getAccessibilityGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string accessibilityGroups = 2;</code>
     * @param value The bytes for accessibilityGroups to set.
     * @return This builder for chaining.
     */
    public Builder setAccessibilityGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessibilityGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object highRiskGroups_ = "";
    /**
     * <code>string highRiskGroups = 3;</code>
     * @return The highRiskGroups.
     */
    public java.lang.String getHighRiskGroups() {
      java.lang.Object ref = highRiskGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        highRiskGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string highRiskGroups = 3;</code>
     * @return The bytes for highRiskGroups.
     */
    public com.google.protobuf.ByteString
        getHighRiskGroupsBytes() {
      java.lang.Object ref = highRiskGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        highRiskGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string highRiskGroups = 3;</code>
     * @param value The highRiskGroups to set.
     * @return This builder for chaining.
     */
    public Builder setHighRiskGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      highRiskGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string highRiskGroups = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHighRiskGroups() {
      
      highRiskGroups_ = getDefaultInstance().getHighRiskGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string highRiskGroups = 3;</code>
     * @param value The bytes for highRiskGroups to set.
     * @return This builder for chaining.
     */
    public Builder setHighRiskGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      highRiskGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object increasedInterestGroups_ = "";
    /**
     * <code>string increasedInterestGroups = 4;</code>
     * @return The increasedInterestGroups.
     */
    public java.lang.String getIncreasedInterestGroups() {
      java.lang.Object ref = increasedInterestGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        increasedInterestGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string increasedInterestGroups = 4;</code>
     * @return The bytes for increasedInterestGroups.
     */
    public com.google.protobuf.ByteString
        getIncreasedInterestGroupsBytes() {
      java.lang.Object ref = increasedInterestGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        increasedInterestGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string increasedInterestGroups = 4;</code>
     * @param value The increasedInterestGroups to set.
     * @return This builder for chaining.
     */
    public Builder setIncreasedInterestGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      increasedInterestGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string increasedInterestGroups = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncreasedInterestGroups() {
      
      increasedInterestGroups_ = getDefaultInstance().getIncreasedInterestGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string increasedInterestGroups = 4;</code>
     * @param value The bytes for increasedInterestGroups to set.
     * @return This builder for chaining.
     */
    public Builder setIncreasedInterestGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      increasedInterestGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object insiderInfoGroups_ = "";
    /**
     * <code>string insiderInfoGroups = 5;</code>
     * @return The insiderInfoGroups.
     */
    public java.lang.String getInsiderInfoGroups() {
      java.lang.Object ref = insiderInfoGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        insiderInfoGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string insiderInfoGroups = 5;</code>
     * @return The bytes for insiderInfoGroups.
     */
    public com.google.protobuf.ByteString
        getInsiderInfoGroupsBytes() {
      java.lang.Object ref = insiderInfoGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        insiderInfoGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string insiderInfoGroups = 5;</code>
     * @param value The insiderInfoGroups to set.
     * @return This builder for chaining.
     */
    public Builder setInsiderInfoGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      insiderInfoGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string insiderInfoGroups = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInsiderInfoGroups() {
      
      insiderInfoGroups_ = getDefaultInstance().getInsiderInfoGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string insiderInfoGroups = 5;</code>
     * @param value The bytes for insiderInfoGroups to set.
     * @return This builder for chaining.
     */
    public Builder setInsiderInfoGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      insiderInfoGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object investorInfoGroups_ = "";
    /**
     * <code>string investorInfoGroups = 6;</code>
     * @return The investorInfoGroups.
     */
    public java.lang.String getInvestorInfoGroups() {
      java.lang.Object ref = investorInfoGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investorInfoGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string investorInfoGroups = 6;</code>
     * @return The bytes for investorInfoGroups.
     */
    public com.google.protobuf.ByteString
        getInvestorInfoGroupsBytes() {
      java.lang.Object ref = investorInfoGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investorInfoGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string investorInfoGroups = 6;</code>
     * @param value The investorInfoGroups to set.
     * @return This builder for chaining.
     */
    public Builder setInvestorInfoGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      investorInfoGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string investorInfoGroups = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvestorInfoGroups() {
      
      investorInfoGroups_ = getDefaultInstance().getInvestorInfoGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string investorInfoGroups = 6;</code>
     * @param value The bytes for investorInfoGroups to set.
     * @return This builder for chaining.
     */
    public Builder setInvestorInfoGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      investorInfoGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pfrGroups_ = "";
    /**
     * <code>string pfrGroups = 7;</code>
     * @return The pfrGroups.
     */
    public java.lang.String getPfrGroups() {
      java.lang.Object ref = pfrGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pfrGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pfrGroups = 7;</code>
     * @return The bytes for pfrGroups.
     */
    public com.google.protobuf.ByteString
        getPfrGroupsBytes() {
      java.lang.Object ref = pfrGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pfrGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pfrGroups = 7;</code>
     * @param value The pfrGroups to set.
     * @return This builder for chaining.
     */
    public Builder setPfrGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pfrGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pfrGroups = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPfrGroups() {
      
      pfrGroups_ = getDefaultInstance().getPfrGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string pfrGroups = 7;</code>
     * @param value The bytes for pfrGroups to set.
     * @return This builder for chaining.
     */
    public Builder setPfrGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pfrGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productGroups_ = "";
    /**
     * <code>string productGroups = 8;</code>
     * @return The productGroups.
     */
    public java.lang.String getProductGroups() {
      java.lang.Object ref = productGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productGroups = 8;</code>
     * @return The bytes for productGroups.
     */
    public com.google.protobuf.ByteString
        getProductGroupsBytes() {
      java.lang.Object ref = productGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productGroups = 8;</code>
     * @param value The productGroups to set.
     * @return This builder for chaining.
     */
    public Builder setProductGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productGroups = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductGroups() {
      
      productGroups_ = getDefaultInstance().getProductGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string productGroups = 8;</code>
     * @param value The bytes for productGroups to set.
     * @return This builder for chaining.
     */
    public Builder setProductGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vipClientCategoryGroups_ = "";
    /**
     * <code>string vipClientCategoryGroups = 9;</code>
     * @return The vipClientCategoryGroups.
     */
    public java.lang.String getVipClientCategoryGroups() {
      java.lang.Object ref = vipClientCategoryGroups_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vipClientCategoryGroups_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vipClientCategoryGroups = 9;</code>
     * @return The bytes for vipClientCategoryGroups.
     */
    public com.google.protobuf.ByteString
        getVipClientCategoryGroupsBytes() {
      java.lang.Object ref = vipClientCategoryGroups_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vipClientCategoryGroups_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vipClientCategoryGroups = 9;</code>
     * @param value The vipClientCategoryGroups to set.
     * @return This builder for chaining.
     */
    public Builder setVipClientCategoryGroups(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vipClientCategoryGroups_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vipClientCategoryGroups = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearVipClientCategoryGroups() {
      
      vipClientCategoryGroups_ = getDefaultInstance().getVipClientCategoryGroups();
      onChanged();
      return this;
    }
    /**
     * <code>string vipClientCategoryGroups = 9;</code>
     * @param value The bytes for vipClientCategoryGroups to set.
     * @return This builder for chaining.
     */
    public Builder setVipClientCategoryGroupsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vipClientCategoryGroups_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object visionGroup_ = "";
    /**
     * <code>string visionGroup = 10;</code>
     * @return The visionGroup.
     */
    public java.lang.String getVisionGroup() {
      java.lang.Object ref = visionGroup_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        visionGroup_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string visionGroup = 10;</code>
     * @return The bytes for visionGroup.
     */
    public com.google.protobuf.ByteString
        getVisionGroupBytes() {
      java.lang.Object ref = visionGroup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        visionGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string visionGroup = 10;</code>
     * @param value The visionGroup to set.
     * @return This builder for chaining.
     */
    public Builder setVisionGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      visionGroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string visionGroup = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisionGroup() {
      
      visionGroup_ = getDefaultInstance().getVisionGroup();
      onChanged();
      return this;
    }
    /**
     * <code>string visionGroup = 10;</code>
     * @param value The bytes for visionGroup to set.
     * @return This builder for chaining.
     */
    public Builder setVisionGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      visionGroup_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PartyGroups)
  }

  // @@protoc_insertion_point(class_scope:PartyGroups)
  private static final com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups();
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartyGroups>
      PARSER = new com.google.protobuf.AbstractParser<PartyGroups>() {
    @java.lang.Override
    public PartyGroups parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartyGroups(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartyGroups> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartyGroups> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroups getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

