// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

public interface PartyGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PartyGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partyGroupDictCode = 1;</code>
   * @return The partyGroupDictCode.
   */
  java.lang.String getPartyGroupDictCode();
  /**
   * <code>string partyGroupDictCode = 1;</code>
   * @return The bytes for partyGroupDictCode.
   */
  com.google.protobuf.ByteString
      getPartyGroupDictCodeBytes();
}
