// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: methodSearchByF.proto

package com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio;

/**
 * Protobuf type {@code PartyGroup}
 */
public final class PartyGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PartyGroup)
    PartyGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartyGroup.newBuilder() to construct.
  private PartyGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartyGroup() {
    partyGroupDictCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartyGroup();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartyGroup(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            partyGroupDictCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder.class);
  }

  public static final int PARTYGROUPDICTCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object partyGroupDictCode_;
  /**
   * <code>string partyGroupDictCode = 1;</code>
   * @return The partyGroupDictCode.
   */
  @java.lang.Override
  public java.lang.String getPartyGroupDictCode() {
    java.lang.Object ref = partyGroupDictCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partyGroupDictCode_ = s;
      return s;
    }
  }
  /**
   * <code>string partyGroupDictCode = 1;</code>
   * @return The bytes for partyGroupDictCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartyGroupDictCodeBytes() {
    java.lang.Object ref = partyGroupDictCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partyGroupDictCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPartyGroupDictCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, partyGroupDictCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPartyGroupDictCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, partyGroupDictCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup)) {
      return super.equals(obj);
    }
    com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup other = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup) obj;

    if (!getPartyGroupDictCode()
        .equals(other.getPartyGroupDictCode())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARTYGROUPDICTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getPartyGroupDictCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PartyGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PartyGroup)
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.class, com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.Builder.class);
    }

    // Construct using com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      partyGroupDictCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.MethodSearchByF.internal_static_PartyGroup_descriptor;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getDefaultInstanceForType() {
      return com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.getDefaultInstance();
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup build() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup buildPartial() {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup result = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup(this);
      result.partyGroupDictCode_ = partyGroupDictCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup) {
        return mergeFrom((com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup other) {
      if (other == com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup.getDefaultInstance()) return this;
      if (!other.getPartyGroupDictCode().isEmpty()) {
        partyGroupDictCode_ = other.partyGroupDictCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object partyGroupDictCode_ = "";
    /**
     * <code>string partyGroupDictCode = 1;</code>
     * @return The partyGroupDictCode.
     */
    public java.lang.String getPartyGroupDictCode() {
      java.lang.Object ref = partyGroupDictCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partyGroupDictCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partyGroupDictCode = 1;</code>
     * @return The bytes for partyGroupDictCode.
     */
    public com.google.protobuf.ByteString
        getPartyGroupDictCodeBytes() {
      java.lang.Object ref = partyGroupDictCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partyGroupDictCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partyGroupDictCode = 1;</code>
     * @param value The partyGroupDictCode to set.
     * @return This builder for chaining.
     */
    public Builder setPartyGroupDictCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partyGroupDictCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partyGroupDictCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartyGroupDictCode() {
      
      partyGroupDictCode_ = getDefaultInstance().getPartyGroupDictCode();
      onChanged();
      return this;
    }
    /**
     * <code>string partyGroupDictCode = 1;</code>
     * @param value The bytes for partyGroupDictCode to set.
     * @return This builder for chaining.
     */
    public Builder setPartyGroupDictCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partyGroupDictCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PartyGroup)
  }

  // @@protoc_insertion_point(class_scope:PartyGroup)
  private static final com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup();
  }

  public static com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartyGroup>
      PARSER = new com.google.protobuf.AbstractParser<PartyGroup>() {
    @java.lang.Override
    public PartyGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartyGroup(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartyGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartyGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stub.stub_Rest_gRPC.serviceGRPC.serviceSearchByF_Fio.PartyGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

